name: Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
          - DaftIe
          - DngIe
          - MyHomeIe
          - PropertyPalCom
          - SherryFitzIe

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Set environment
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "ENV=production" >> "$GITHUB_ENV"
          else
              echo "ENV=other" >> "$GITHUB_ENV"
          fi

      - name: Run
        run: sbt -v "scraper/run ${{ matrix.project }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_READ_PACKAGES }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  aggregate:
    needs: scrape

    name: Aggregate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Set environment
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "ENV=production" >> "$GITHUB_ENV"
          else
              echo "ENV=other" >> "$GITHUB_ENV"
          fi

      - name: Run
        run: sbt -v aggregate/run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_READ_PACKAGES }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
