name: Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        run:
          - scraper/run DaftIe
          - scraper/run DngIe
          - scraper/run MyHomeIe
          - scraper/run PropertyPalCom
          - scraper/run SherryFitzIe
          - scraper/run MaherPropertyIe

          - scraper2/run AbbeyPropertySalesCom
          - scraper2/run AlanBrowneEstatesIe
          - scraper2/run AllenAndJacobsIe
          - scraper2/run AmoveIe
          - scraper2/run FiveSIe

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Set environment to production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "ENV=production" >> $GITHUB_ENV

      - name: Run
        run: sbt -v "${{ matrix.run }}"
        env:
          ENV: ${{ env.ENV }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_READ_PACKAGES }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  aggregate:
    if: ${{ always() }}
    needs: scrape

    name: Aggregate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Set environment to production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "ENV=production" >> $GITHUB_ENV

      - name: Run
        run: sbt -v aggregate/run
        env:
          ENV: ${{ env.ENV }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_READ_PACKAGES }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  seo:
    if: ${{ always() }}
    needs: aggregate

    name: Search Engine Optimization
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Set environment to production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "ENV=production" >> $GITHUB_ENV

      - name: Run
        run: sbt -v seo/run
        env:
          ENV: ${{ env.ENV }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_READ_PACKAGES }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
