name: Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  schedule:
    name: Schedule
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
          - 'daft'
          - 'douglasNewmanGood'
          - 'myHome'
          - 'propertyPal'
          - 'sherryFitzGerald'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Run
        run: sbt -v "${{ matrix.project }}/run"
        env:
          ENV: production
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_READ_PACKAGES }}
          GCP_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
