name: Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  schedule:
    name: Schedule
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Run
        run: sbt -v run

      - name: Send notification on failure
        if: ${{ failure() }}
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: ${{ secrets.FROM_NUMBER }}
          toPhoneNumber: ${{ secrets.TO_NUMBER }}
          message: ${{ github.job }} job of ${{ github.repository }} has a ${{ job.status }}
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
